/-
Copyright (c) 2026 Lean FRO, LLC. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Paul Reichert
-/
module

prelude
public import Lean.EnvExtension

public section

namespace Lean

/--
Registered by `newtype N := Nat with toNat`, so that `whnf` and `isDefEq` treat `N.toNat (N.mk a)`
and `N.mk (N.toNat x)` like iota and eta for a one-field structure, although `N`, `N.mk` and
`N.toNat` are irreducible definitions.
-/
structure VirtualStructureInfo where
  typeName : Name
  ctorName : Name
  projName : Name
  /-- The number of parameters of `typeName`, which `ctorName` and `projName` take first. -/
  numParams : Nat
  deriving Inhabited, Repr

builtin_initialize virtualStructureTypeExt : MapDeclarationExtension VirtualStructureInfo ←
  mkMapDeclarationExtension
builtin_initialize virtualStructureCtorExt : MapDeclarationExtension VirtualStructureInfo ←
  mkMapDeclarationExtension
builtin_initialize virtualStructureProjExt : MapDeclarationExtension VirtualStructureInfo ←
  mkMapDeclarationExtension

/-- Registers `info` under its type, constructor and projector names, so all three can be looked
up from any of them. -/
def registerVirtualStructure (env : Environment) (info : VirtualStructureInfo) : Environment :=
  let env := virtualStructureTypeExt.insert env info.typeName info
  let env := virtualStructureCtorExt.insert env info.ctorName info
  virtualStructureProjExt.insert env info.projName info

namespace Environment

/-- If `typeName` was declared via `newtype`, return its virtual structure info. -/
def getVirtualStructureInfo? (env : Environment) (typeName : Name) : Option VirtualStructureInfo :=
  virtualStructureTypeExt.find? env typeName

/-- If `ctorName` is the constructor auto-generated by `newtype`, return its virtual structure
info. -/
def getVirtualCtorInfo? (env : Environment) (ctorName : Name) : Option VirtualStructureInfo :=
  virtualStructureCtorExt.find? env ctorName

/-- If `projName` is the projector auto-generated by `newtype`, return its virtual structure
info. -/
def getVirtualProjInfo? (env : Environment) (projName : Name) : Option VirtualStructureInfo :=
  virtualStructureProjExt.find? env projName

end Environment

def getVirtualStructureInfo? [Monad m] [MonadEnv m] (typeName : Name) :
    m (Option VirtualStructureInfo) :=
  return (← getEnv).getVirtualStructureInfo? typeName

def getVirtualCtorInfo? [Monad m] [MonadEnv m] (ctorName : Name) : m (Option VirtualStructureInfo) :=
  return (← getEnv).getVirtualCtorInfo? ctorName

def getVirtualProjInfo? [Monad m] [MonadEnv m] (projName : Name) : m (Option VirtualStructureInfo) :=
  return (← getEnv).getVirtualProjInfo? projName

end Lean
