/-
Copyright (c) 2026 Lean FRO, LLC. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Paul Reichert
-/
module

prelude
public import Lean.EnvExtension

public section

namespace Lean

/--
Registered by `newtype N where toNat : Nat`, so that `whnf` and `isDefEq` treat `N.toNat (N.mk a)`
and `N.mk (N.toNat x)` like iota and eta for a one-field structure, although `N`, `N.mk` and
`N.toNat` are irreducible definitions.
-/
structure VirtualStructureInfo where
  typeName : Name
  ctorName : Name
  projName : Name
  /-- The number of parameters of `typeName`, which `ctorName` and `projName` take first. -/
  numParams : Nat
  deriving Inhabited, Repr

/--
State of `virtualStructureExt`, indexed by the type, constructor and projector names. `whnf` and
`isDefEq` look up every constant they get stuck on, so imported entries are put into `SMap`s up
front.
-/
structure VirtualStructureState where
  types : SMap Name VirtualStructureInfo := {}
  ctors : SMap Name VirtualStructureInfo := {}
  projs : SMap Name VirtualStructureInfo := {}
  deriving Inhabited

namespace VirtualStructureState

def addEntry (s : VirtualStructureState) (info : VirtualStructureInfo) : VirtualStructureState :=
  { types := s.types.insert info.typeName info
    ctors := s.ctors.insert info.ctorName info
    projs := s.projs.insert info.projName info }

def switch (s : VirtualStructureState) : VirtualStructureState :=
  { types := s.types.switch, ctors := s.ctors.switch, projs := s.projs.switch }

end VirtualStructureState

builtin_initialize virtualStructureExt :
    SimplePersistentEnvExtension VirtualStructureInfo VirtualStructureState ←
  registerSimplePersistentEnvExtension {
    addEntryFn    := VirtualStructureState.addEntry
    addImportedFn := fun es => (mkStateFromImportedEntries VirtualStructureState.addEntry {} es).switch
    -- Do not export info for private newtypes
    exportEntriesFnEx? := some fun env _ entries =>
      .uniform (entries.toArray.filter (env.contains (skipRealize := false) ·.typeName))
  }

/-- Registers `info` under its type, constructor and projector names, so all three can be looked
up from any of them. -/
def registerVirtualStructure (env : Environment) (info : VirtualStructureInfo) : Environment :=
  virtualStructureExt.addEntry env info

namespace Environment

/-- If `typeName` was declared via `newtype`, return its virtual structure info. -/
def getVirtualStructureInfo? (env : Environment) (typeName : Name) : Option VirtualStructureInfo :=
  (virtualStructureExt.getState env).types.find? typeName

/-- If `ctorName` is the constructor auto-generated by `newtype`, return its virtual structure
info. -/
def getVirtualCtorInfo? (env : Environment) (ctorName : Name) : Option VirtualStructureInfo :=
  (virtualStructureExt.getState env).ctors.find? ctorName

/-- If `projName` is the projector auto-generated by `newtype`, return its virtual structure
info. -/
def getVirtualProjInfo? (env : Environment) (projName : Name) : Option VirtualStructureInfo :=
  (virtualStructureExt.getState env).projs.find? projName

end Environment

def getVirtualStructureInfo? [Monad m] [MonadEnv m] (typeName : Name) :
    m (Option VirtualStructureInfo) :=
  return (← getEnv).getVirtualStructureInfo? typeName

def getVirtualCtorInfo? [Monad m] [MonadEnv m] (ctorName : Name) : m (Option VirtualStructureInfo) :=
  return (← getEnv).getVirtualCtorInfo? ctorName

def getVirtualProjInfo? [Monad m] [MonadEnv m] (projName : Name) : m (Option VirtualStructureInfo) :=
  return (← getEnv).getVirtualProjInfo? projName

end Lean
